[project]
name = "Content-Hub Backend"
version = "0.1.0"
description = "Personal feed aggregator that collects content from RSS feeds and web sources."
readme = "README.md"
requires-python = ">=3.9"
dependencies = []
